openapi: 3.1.0
info:
  title: Enterprise Chatbot Platform API
  version: v1
  description: RESTful API surface for chatbots, conversations, workflows, and analytics.
servers:
  - url: https://api.example.com/api/v1
security:
  - ApiKeyAuth: []
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  parameters:
    Cursor:
      name: cursor
      in: query
      schema:
        type: string
      description: Opaque cursor for pagination.
    Limit:
      name: limit
      in: query
      schema:
        type: integer
        default: 20
        maximum: 100
      description: Max records per page.
  schemas:
    ApiError:
      type: object
      required:
        - status
        - code
        - message
      properties:
        status:
          type: integer
        code:
          type: string
        message:
          type: string
        details:
          type: array
          items:
            type: object
            properties:
              field:
                type: string
              issue:
                type: string
    Meta:
      type: object
      properties:
        count:
          type: integer
        nextCursor:
          type: string
    Chatbot:
      type: object
      required:
        - id
        - workspace_id
        - name
      properties:
        id:
          type: string
        workspace_id:
          type: string
        name:
          type: string
        status:
          type: string
          enum: [draft, active, archived]
        config:
          type: object
        widget_config:
          type: object
        default_workflow_id:
          type: string
        created_at:
          type: string
          format: date-time
    Conversation:
      type: object
      properties:
        id:
          type: string
        chatbot_id:
          type: string
        session_id:
          type: string
        status:
          type: string
          enum: [waiting, active, resolved, bot]
        assigned_to:
          type: string
        priority:
          type: string
        tags:
          type: array
          items:
            type: string
        first_response_time_ms:
          type: integer
        context:
          type: object
    Message:
      type: object
      properties:
        id:
          type: string
        conversation_id:
          type: string
        role:
          type: string
          enum: [user, agent, system, bot]
        content:
          type: string
        citations:
          type: array
          items:
            type: string
        feedback_rating:
          type: integer
    KnowledgeBase:
      type: object
      properties:
        id:
          type: string
        workspace_id:
          type: string
        name:
          type: string
        status:
          type: string
        config:
          type: object
    Workflow:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        status:
          type: string
        nodes:
          type: array
          items:
            type: object
        edges:
          type: array
          items:
            type: object
  responses:
    TooManyRequests:
      description: Rate limit reached
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'
paths:
  /chatbots:
    get:
      summary: List chatbots
      parameters:
        - $ref: '#/components/parameters/Cursor'
        - $ref: '#/components/parameters/Limit'
        - name: workspace_id
          in: query
          schema:
            type: string
        - name: status
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Paginated list
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Chatbot'
                  meta:
                    $ref: '#/components/schemas/Meta'
    post:
      summary: Create a chatbot
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: [workspace_id, name]
              properties:
                workspace_id:
                  type: string
                name:
                  type: string
                config:
                  type: object
                widget_config:
                  type: object
                default_workflow_id:
                  type: string
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Chatbot'
  /chatbots/{chatbotId}:
    get:
      summary: Get chatbot
      parameters:
        - name: chatbotId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Chatbot'
    patch:
      summary: Update chatbot
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                config:
                  type: object
                widget_config:
                  type: object
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Chatbot'
    delete:
      summary: Delete chatbot
      responses:
        '204':
          description: Deleted
  /chatbots/{chatbotId}/publish:
    post:
      summary: Publish chatbot
      responses:
        '200':
          description: Published version
  /conversations:
    get:
      summary: List conversations
      parameters:
        - $ref: '#/components/parameters/Cursor'
        - $ref: '#/components/parameters/Limit'
        - name: status
          in: query
          schema:
            type: string
        - name: channel
          in: query
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Conversation'
                  meta:
                    $ref: '#/components/schemas/Meta'
  /conversations/{conversationId}:
    get:
      summary: Get conversation
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Conversation'
    patch:
      summary: Update conversation
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                tags:
                  type: array
                  items:
                    type: string
                assigned_to:
                  type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Conversation'
  /conversations/{conversationId}/messages:
    post:
      summary: Send a message
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: [role, content]
              properties:
                role:
                  type: string
                content:
                  type: string
                citations:
                  type: array
                  items:
                    type: string
                feedback_rating:
                  type: integer
      responses:
        '201':
          description: Message sent
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
  /knowledge-bases:
    get:
      summary: List knowledge bases
      parameters:
        - $ref: '#/components/parameters/Cursor'
        - $ref: '#/components/parameters/Limit'
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/KnowledgeBase'
                  meta:
                    $ref: '#/components/schemas/Meta'
    post:
      summary: Create KB
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: [workspace_id, name]
              properties:
                workspace_id:
                  type: string
                name:
                  type: string
                config:
                  type: object
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KnowledgeBase'
  /knowledge-bases/{kbId}:
    get:
      summary: Get KB
      parameters:
        - name: kbId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KnowledgeBase'
    patch:
      summary: Update KB
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                config:
                  type: object
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KnowledgeBase'
    delete:
      summary: Delete KB
      responses:
        '204':
          description: Deleted
  /knowledge-bases/{kbId}/upload:
    post:
      summary: Upload documents
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '202':
          description: Upload accepted
  /knowledge-bases/{kbId}/search:
    post:
      summary: Query KB
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                topK:
                  type: integer
                cursor:
                  type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: object
                  meta:
                    $ref: '#/components/schemas/Meta'
  /workflows:
    get:
      summary: List workflows
      parameters:
        - $ref: '#/components/parameters/Cursor'
        - $ref: '#/components/parameters/Limit'
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Workflow'
                  meta:
                    $ref: '#/components/schemas/Meta'
    post:
      summary: Create workflow
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: [name, nodes]
              properties:
                name:
                  type: string
                nodes:
                  type: array
                  items:
                    type: object
                edges:
                  type: array
                  items:
                    type: object
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workflow'
  /workflows/{workflowId}:
    parameters:
      - name: workflowId
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Get workflow
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workflow'
    patch:
      summary: Update workflow
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nodes:
                  type: array
                  items:
                    type: object
                edges:
                  type: array
                  items:
                    type: object
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workflow'
    delete:
      summary: Delete workflow
      responses:
        '204':
          description: Deleted
  /workflows/{workflowId}/publish:
    post:
      summary: Publish workflow
      responses:
        '200':
          description: Published
  /webhooks:
    get:
      summary: List webhooks
      parameters:
        - $ref: '#/components/parameters/Cursor'
        - $ref: '#/components/parameters/Limit'
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                  meta:
                    $ref: '#/components/schemas/Meta'
    post:
      summary: Create webhook
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: [url, events]
              properties:
                url:
                  type: string
                events:
                  type: array
                  items:
                    type: string
                retries:
                  type: integer
      responses:
        '201':
          description: Webhook created
  /webhooks/{webhookId}:
    parameters:
      - name: webhookId
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Get webhook
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
    patch:
      summary: Update webhook
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                events:
                  type: array
                  items:
                    type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
    delete:
      summary: Delete webhook
      responses:
        '204':
          description: Deleted
  /webhooks/{webhookId}/test:
    post:
      summary: Send a test webhook
      responses:
        '202':
          description: Test queued
  /analytics/metrics:
    get:
      summary: Analytics overview
      parameters:
        - name: from
          in: query
          schema:
            type: string
            format: date
        - name: to
          in: query
          schema:
            type: string
            format: date
        - name: chatbot_id
          in: query
          schema:
            type: string
        - name: channel
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Metrics payload
          content:
            application/json:
              schema:
                type: object
                properties:
                  conversations:
                    type: object
                  messages:
                    type: object
                  satisfaction:
                    type: object
